### PR TITLE
packaging with a setup.py and proper package hierarchy

### PR DESCRIPTION
**Pull request by cgoldberg**
it's now a python package!

to develop inside a virtualenv:
(env)$ pip install -e .

to run the tests:
(env)$ python -m unittest discover

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @cgoldberg! I've created [OSPR-1193](https://openedx.atlassian.net/browse/OSPR-1193) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/harprofiler/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@benpatterson @cpennington any opinions about what to do with this 16-month old pull request?

**Comment by cpennington** [comment]
Fix the conflicts and merge it?

**Comment by benpatterson** [comment]
That all sounds fine but we're not using this tool so cleaning this up is
not a priority right now. You guys are welcome to do it.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @cgoldberg! I've created [OSPR-1228](https://openedx.atlassian.net/browse/OSPR-1228) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/harprofiler/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
Not sure why the bot chose to make a ticket now. I'm closing the ticket.

**Pull request closed without merging**
